version: 1.0.{build}

os: Visual Studio 2017

environment:
  matrix:
  - MSVC_ARCH: x64
    BOOST_ROOT: C:\Libraries\boost_1_67_0
    BOOST_INCLUDEDIR: C:\Libraries\boost_1_67_0\boost
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_67_0\lib64-msvc-15.0
    CMAKE_GENERATOR: 'Visual Studio 15 2017'

configuration: Release

build_script:
- set PATH=%BOOST_LIBRARYDIR%;%PATH%
- cmake -E make_directory build
- cmake -E chdir build cmake -G "%CMAKE_GENERATOR%" -A "%MSVC_ARCH%" -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_INCLUDEDIR="%BOOST_INCLUDEDIR%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" ..
- cmake --build build

artifacts:
- path: evoke.exe

